"use client";

import Link from "next/link";
import { AlertTriangle, BarChart3, ClipboardCheck, GitMerge, Route, UsersRound } from "lucide-react";
import { useDemoDb } from "@/lib/hooks";
import { numberId } from "@/lib/format";

export default function AdminDashboard(){const db=useDemoDb();if(!db)return null;const pending=db.users.filter(u=>u.verificationStatus==="pending");const openFlags=db.moderation.filter(f=>f.status==="open");return <>
<div className="dash-hero"><section className="welcome-card"><span className="eyebrow" style={{color:"#f5bb4d"}}>Admin control</span><h2>Jaga aturan. Jaga kepercayaan ekosistem.</h2><p>Admin tidak mengubah hasil model secara diam-diam. Peran admin berfokus pada verifikasi, rule version, moderasi, dan audit dampak.</p><Link href="/admin/verifikasi" className="btn btn-orange"><ClipboardCheck size={17}/> Tinjau Verifikasi</Link></section><aside className="quick-card"><span>Perlu perhatian</span><strong>{pending.length+openFlags.length}</strong><span>{pending.length} verifikasi · {openFlags.length} moderation flag terbuka.</span></aside></div>
<div className="stats-grid"><div className="stat-card"><div className="stat-card-head"><span>Pengguna</span><span className="stat-icon"><UsersRound size={18}/></span></div><strong>{db.users.length}</strong><small>petani, buyer, admin</small></div><div className="stat-card"><div className="stat-card-head"><span>Routing rules</span><span className="stat-icon"><Route size={18}/></span></div><strong>{db.rules.filter(r=>r.active).length}</strong><small>rule aktif</small></div><div className="stat-card"><div className="stat-card-head"><span>Pool</span><span className="stat-icon"><GitMerge size={18}/></span></div><strong>{db.pools.length}</strong><small>{db.pools.filter(p=>p.status==="ready").length} ready</small></div><div className="stat-card"><div className="stat-card-head"><span>Kg dianalisis</span><span className="stat-icon"><BarChart3 size={18}/></span></div><strong>{numberId(db.impact.analyzedKg)}</strong><small>ledger demo</small></div></div>
<div className="dash-grid"><section className="dash-panel"><div className="panel-head"><h2>Verifikasi tertunda</h2><Link href="/admin/verifikasi">Kelola</Link></div>{pending.length?<div className="list-stack">{pending.map(u=><div className="list-item" key={u.id}><div className="list-item-main"><b>{u.name}</b><small>{u.organization} · {u.role}</small></div><span className="status pending">pending</span></div>)}</div>:<div className="empty-state">Tidak ada verifikasi tertunda.</div>}</section><aside className="dash-panel"><div className="panel-head"><h2>Moderation flags</h2><Link href="/admin/moderasi">Kelola</Link></div>{openFlags.map(f=><div className="list-item" key={f.id}><div className="list-item-main"><b>{f.targetType}</b><small>{f.reason}</small></div><AlertTriangle size={18}/></div>)}</aside></div>
</>}
