"use client";

import Link from "next/link";
import { Boxes, FileSearch, HandCoins, PackagePlus } from "lucide-react";
import { useDemoDb, useSessionUser } from "@/lib/hooks";
import { commodityLabel, dateId, numberId, rupiah } from "@/lib/format";

export default function BuyerDashboard(){const db=useDemoDb();const user=useSessionUser();if(!db||!user)return null;const demands=db.demands.filter(d=>d.buyerId===user.id);const offers=db.offers.filter(o=>o.buyerId===user.id);const open=offers.filter(o=>o.status==="pending");return <>
<div className="dash-hero"><section className="welcome-card"><span className="eyebrow" style={{color:"#f5bb4d"}}>Buyer workspace</span><h2>Buka kebutuhan. Temukan pasokan yang cocok.</h2><p>Tentukan kondisi yang diterima, volume minimum, radius, deadline, dan offer per kg. Sistem memprioritaskan kompatibilitas sebelum nilai ekonomi.</p><Link href="/buyer/demand/baru" className="btn btn-orange"><PackagePlus size={17}/> Buat Demand</Link></section><aside className="quick-card"><span>Demand aktif</span><strong>{demands.filter(d=>d.status==="active").length}</strong><span>{open.length} offer menunggu keputusan buyer.</span></aside></div>
<div className="stats-grid"><div className="stat-card"><div className="stat-card-head"><span>Total demand</span><span className="stat-icon"><Boxes size={18}/></span></div><strong>{demands.length}</strong><small>termasuk active/paused</small></div><div className="stat-card"><div className="stat-card-head"><span>Batch tersedia</span><span className="stat-icon"><FileSearch size={18}/></span></div><strong>{db.batches.filter(b=>b.routingStatus==="READY").length}</strong><small>dapat dihitung match</small></div><div className="stat-card"><div className="stat-card-head"><span>Offer masuk</span><span className="stat-icon"><HandCoins size={18}/></span></div><strong>{offers.length}</strong><small>{open.length} pending</small></div><div className="stat-card"><div className="stat-card-head"><span>Volume demand</span><span className="stat-icon"><PackagePlus size={18}/></span></div><strong>{numberId(demands.reduce((s,d)=>s+d.minimumVolumeKg,0))} kg</strong><small>minimum volume gabungan</small></div></div>
<div className="dash-grid"><section className="dash-panel"><div className="panel-head"><h2>Demand aktif</h2><Link href="/buyer/demand/baru">Tambah</Link></div><div className="table-wrap"><table><thead><tr><th>Komoditas</th><th>Kondisi</th><th>Volume</th><th>Offer/kg</th><th>Deadline</th><th>Status</th></tr></thead><tbody>{demands.map(d=><tr key={d.id}><td><b>{commodityLabel[d.commodity]}</b></td><td>{d.acceptedConditions.join(", ")}</td><td>{numberId(d.minimumVolumeKg)} kg</td><td>{rupiah(d.offerPricePerKg)}</td><td>{dateId(d.deadline)}</td><td><span className={`status ${d.status}`}>{d.status}</span></td></tr>)}</tbody></table></div></section><aside className="dash-panel"><div className="panel-head"><h2>Offer terbaru</h2><Link href="/buyer/offers">Kelola</Link></div><div className="list-stack">{offers.slice(0,5).map(o=><div className="list-item" key={o.id}><div className="list-item-main"><b>{numberId(o.acceptedWeightKg)} kg · {rupiah(o.offeredPricePerKg)}/kg</b><small>Potential {rupiah(o.acceptedWeightKg*o.offeredPricePerKg)}</small></div><span className={`status ${o.status}`}>{o.status}</span></div>)}</div></aside></div>
</>}
